<html lang="en-GB">
    <head>
        <link href="css/styles.css" rel="stylesheet" type="text/css" />
        <link href="css/mainView.css" rel="stylesheet" type="text/css" />
        <script src="js/index.js" defer></script>
    </head>
    <body>
        <?php include_once 'navBar.phtml'; ?>
        <main>
            <h1>How to use this todo app</h1>
            <ul>
                <li>Add a new todo by typing one in on last line of the todos page and pressing enter.</li>
                <li>Edit a todo by editing its text and pressing enter.</li>
                <li>Delete a todo by deleting all its text and pressing backspace.</li>
                <li>Do the same with todo tags on the tags page.</li>
                <li>Toggle the marking of a todo as done by shift-clicking it.</li>
                <li>Toggle the tagging of a todo as done by shift-clicking a tag.</li>
                <li>Toggle the tag filtering of the todo page by shift-clicking a tag.</li>
            </ul>
        </main>
    </body>
</html>