<?php

    $tagListHTML = \App\ViewHelpers\ViewTagsHelper::displayAllTags($tags);
    $tagListHTML .= \App\ViewHelpers\ViewTagsHelper::displayNewTag();

?>

<html lang="en-GB">
    <head>
        <link href="styles.css" rel="stylesheet" type="text/css" />
        <link href="tagsView.css" rel="stylesheet" type="text/css" />
        <script src="tagsView.js" defer></script>
    </head>
    <body>
        <a href="/">Back</a>
        <?= $tagListHTML; ?>
    </body>
</html>