<?php

    $todoListHTML = \App\ViewHelpers\ViewTodosHelper::displayAllTodos($todos, $tags, $filterTags ?? '');
    $todoListHTML .= \App\ViewHelpers\ViewTodosHelper::displayNewTodo();

?>
<html lang="en-GB">
    <head>
        <title>Todos - Todos</title>
        <link href="css/styles.css" rel="stylesheet" type="text/css" />
        <script src="js/index.js" defer></script>
        <script src="js/todosView.js" defer></script>
    </head>
    <body>
        <?php include_once 'navBar.phtml'; ?>
        <main>
            <?= $todoListHTML; ?>
        </main>
    </body>
</html>